---
title: "Tarea 10"
author: "Martin Santamaria"
date: "24/8/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
Sys.setenv(RETICULATE_PYTHON = "/Python38")
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
```

### Ley De Benford

Sea $X \sim Benford$ donde $D_X = \{1,2,3,4,5,6,7,8,9\}$ 

d) Defino aquí varias funciones que utilizaré luego

```{r}
# Función de probabilidad
dben = function(x){
  if(x >= 1 && x <= 9){
    sapply(x,function(x){log10(x + 1) - log10(x);});
  }else{
    0;
  }
}

# Función de distribución
pben = function(x){
  sapply(x,FUN=function(y){if(y < 1){return(0);}
    else if(y >= 9){
      return(1);
    }else{
      return(sum(dben(c(1:y))));}
    });
}

# Media
mben = function(){
  sum(sapply(c(1:9),function(x){x*(log10(x + 1) - log10(x));}));
}

# Varianza
vben = function(){
  s <- sum(sapply(c(1:9),function(x){x^2*(log10(x + 1) - log10(x));}));
  s - mben()^2
}
```

a) 

$$E(X)=\sum_{x\in X(\Omega)} x\cdot P_{X}(x)$$

```{r}
mben()
```

$$Var(X)=E(X^2)-(E(X))^2$$

```{r}
vben()
```

b)

$$F_{X}(x_0)=\sum_{x\leq x_0} P_{X}(x)$$

Por ejemplo, calculamos $P(X \le 7)$

```{r}
pben(7)
```

c)

```{r}
dben(c(1:9))
```

Claramente vemos que el dígito con mayor probabilidad (y muy posiblemente la moda en una muestra) es el 1.

e)

```{r}
par(mfrow=c(1,2))

plot(x=c(1:9),
     y=dben(c(1:9)),
     ylim=c(0,0.5),
     xlim=c(1,9),
     xlab="x",
     pch = 19,
     col = 'blue',
     main="Función de probabilidad\n Benford")
lines(x=c(1,2,3,4,5,6,7,8,9),
      y=c(dben(1),dben(2),dben(3),dben(4),dben(5),dben(6),dben(7),dben(8),dben(9)), 
      type = "h", 
      lty = 2,
      col="blue")
axis(1,seq(1,9,1))

curve(pben(x),
      xlim=c(1,9),
      col="blue",
      main="Función de distribución\n Benford")
axis(1,seq(1,9,1))
```

### Distribución de Pareto (Power law)

